name: CI

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ocm CLI
        run: curl -sfL https://ocm.software/install-cli.sh | bash

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Build
        run: task build

      - name: Inspect
        run: task ocm:inspect
